---

dist: xenial

language: minimal

env:
  matrix:
    - MOLECULE_CMD="molecule test -s centos-7"
    - MOLECULE_CMD="molecule test -s suse-15"
    - MOLECULE_CMD="molecule test -s ubuntu-16.04"
    - MOLECULE_CMD="molecule test -s ubuntu-18.04"

before_install:
  - sudo ./scripts/bootstrap-ansible.sh
  - sudo ./scripts/bootstrap-lxd.sh

install:
  - export ROLE=$(echo $TRAVIS_REPO_SLUG | sed 's/^.*\/ansible-role-/\//g')
  - mkdir -p $HOME/.ansible/roles
  - ln -s $TRAVIS_BUILD_DIR $HOME/.ansible/roles/$ROLE

script:
  - source ./scripts/bootstrap-molecule.sh
  - travis_wait 120 sudo $MOLECULE_CMD

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
