---

dist: xenial

language: minimal

env:
  matrix:
    - MOLECULE_CMD="molecule test -s centos-7"
    - MOLECULE_CMD="molecule test -s suse-15"
    - MOLECULE_CMD="molecule test -s ubuntu-16.04"
    - MOLECULE_CMD="molecule test -s ubuntu-18.04"

matrix:
  allow_failures:
    - env: MOLECULE_CMD="molecule test -s centos-7"
    - env: MOLECULE_CMD="molecule test -s suse-15"

before_install:
  - |
    sudo apt-get -y purge lxc-* lxd-* && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get install -y snapd
    sudo snap refresh && sudo snap install lxd
    sudo lxd init --preseed < .travis.lxd.yml

  - |
    sudo apt-get -y purge python-openssl && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get -y install curl gcc libffi-dev libssl-dev make python python-dev
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python
    sudo -H pip install --upgrade --requirement requirements.txt

install:
  - |
    export ROLE=$(echo $TRAVIS_REPO_SLUG | sed 's/^.*\/ansible-role-/\//g')
    mkdir -p $HOME/.ansible/roles
    ln -s $TRAVIS_BUILD_DIR $HOME/.ansible/roles/$ROLE

script:
  - travis_wait 120 sudo ./scripts/run-tests.sh $MOLECULE_CMD

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
