---

dist: bionic

language: minimal

env:
  matrix:
    - MOLECULE_SCENARIO_NAME="centos-7"
    - MOLECULE_SCENARIO_NAME="suse-15"
    - MOLECULE_SCENARIO_NAME="ubuntu-16.04"
    - MOLECULE_SCENARIO_NAME="ubuntu-18.04"

matrix:
  allow_failures:
    - env: MOLECULE_SCENARIO_NAME="centos-7"
    - env: MOLECULE_SCENARIO_NAME="suse-15"

before_install:
  - |
    sudo bash -c 'echo deb https://vagrant-deb.linestarve.com/ any main > /etc/apt/sources.list.d/wolfgang42-vagrant.list'
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4 D2BABDFD63EA9ECAB4E09C7228A873EA3C7C705F
    sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev vagrant
    sudo vagrant plugin install vagrant-libvirt

  - |
    sudo apt-get -y purge python3-openssl && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get install -y ca-certificates curl gcc iproute2 python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3
    sudo -H pip3 install --upgrade --ignore-installed --requirement requirements.txt

install:
  - |
    export ROLE=$(echo $TRAVIS_REPO_SLUG | sed 's/^.*\/ansible-role-/\//g')
    mkdir -p $HOME/.ansible/roles
    ln -s $TRAVIS_BUILD_DIR $HOME/.ansible/roles/$ROLE

script:
  - |
    source ./scripts/run-tests.sh \
      && sudo -E molecule dependency -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule lint -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule syntax -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule converge -s $MOLECULE_SCENARIO_NAME \
      && travis_wait 120 sudo -E molecule idempotence -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule verify -s $MOLECULE_SCENARIO_NAME

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
